### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by marc6030** [Wistoft2410/Digital-design---Spilprojekt#14]
Nedtæller

**Comment by Axedyson** [comment]
En ny person skal **assignes** til denne issue, da den skal testes af en ny person!

**Comment by SimonAxelsen** [comment]
**Nedtælling test**
For en test af denne timer på 10 sekunder, så har jeg brugt en sekundær stopur fra  [](https://www.timeanddate.com/stopwatch/) og sammelignet de to tider, og kan konkludere at nedtællingen fra rød til grøn kører i et interval på 10 sekunder. 

Placeringen af timern er midt i skærmen, helt oppe i toppen, som er en god placering indtil videre, da vi ikke har lavet nogen fugl som smidder æggene, men de falder bare ned. I senere interationer vil placeringen dog rykket ud i en bedre placering.
