### ISSUE TITLE
Sound effects/baggrundsmusik

### ISSUE THREAD

**Issue by SimonAxelsen** [Wistoft2410/Digital-design---Spilprojekt#21]
# Sound effects/baggrundsmusik  
### Forventet tid: 120 minutter
Der skal være sound effects når spillern får point, og når spillern mister liv.
Der skal være baggrundsmusik når startmenuen er fremme, og skal stoppe når spillet starter.

**Comment by Axedyson** [comment]
**Test af Sound effects/baggrundsmusik**
Der er i alt tre forskellige lyde:
- En ding lyd effekt når man snupper et æg.
- En *bruh* lyd effekt når man bliver ramt af en meteor.
- Og til sidst musikken i baggrunden.

Alt virker godt og sådan som det skal. Der er ikke fundet nogen bugs og det giver også god mening da disse lyde sker i baggrunden og er ikke en særlig stor del af spil mekanikken, ligesom baggrunden heller ikke er en særlig stor del af det.
