### ISSUE TITLE
Collision with meteorer

### ISSUE THREAD

**Issue by Wistoft2410** [Wistoft2410/Digital-design---Spilprojekt#22]
# Collision with meteor
### Forventet tid: 60 minutter 
Vores genereret meteor skal kunne kollidere med vores player, når disse meteor kollidere med player skal player miste halvt health point

**Comment by Axedyson** [comment]
Der er blevet lavet en lille afvigelse fra denne task:
lige nu mister spilleren et **helt** liv fremfor et **halvt** liv fordi det lige nu ser lidt svært ud at vise et halvt hjerte i `Heart.pde` filen.

Men meteorerne kan nu kollidere med spilleren og spilleren mister altså **et helt liv/hjerte** for hver gang det sker!

**Comment by SimonAxelsen** [comment]
**Test af kollation med spillern**
Kollation mellem spillern og meteoren virker som den skal. 
Som også er skrevet i issue 5 test, så kan der komme lyd effect når man bliver ramt, da det ellers kan være svært at vide at man bliver ramt.
Det eneste problem som jeg kan se er at hitboxen på spillern er den samme som hos æggne, og den kan være lidt større end selve figuern.
