### ISSUE TITLE
Collision with eggs

### ISSUE THREAD

**Issue by Axedyson** [Wistoft2410/Digital-design---Spilprojekt#24]
# Task: Collision with eggs
### Forventet tid: 45 minutter
Æggene skal kunne kollidere med Dinoen på en sådan måde at æggene skal forsvinde langsomt så det ser ud som om de bliver spist af Dino'en. Æggene skal selvfølgelig også fjernes fra hukommelsen (ArrayList'en). For hvergang at Dino'en optager et æg så score man et point!

**Comment by Axedyson** [comment]
Jeg vil sige jeg er blevet færdig. Det er lidt svært at se om de forsvinder. Prøv og hoppe efter et æg, så burde det gerne forsvinde sådan lidt efter lidt!

**Comment by marc6030** [comment]
**Test af Collision**
Den forsvinder først lidt efter man har ramt ægget. Jeg har test om man får point hver gang man rammer et æg, og det gør man, hvilket er godt. Men får dog ikke point som vises på skærmen, men man kan se det i consolen.

Den skal forsvinde lige når man røre ægget. og pointsystemet skal kunne ses i selve spillet.
