### ISSUE TITLE
Default objekt i spillets verden

### ISSUE THREAD

**Issue by marc6030** [Wistoft2410/Digital-design---Spilprojekt#25]
# Task: Default objekt i spillets verden
### Forventet tid: 120 minutter
Lave en parent classe som bliver brugt til at lave alle opjekterne/genstande i vores spil. Den klasse skal indholde:
Pvector loc;
Pvector vel
Pvector acc

**Comment by SimonAxelsen** [comment]
**Test af default parent class**
For at teste denne parent class, har jeg bare sammelignet kodens udseende får parent class er blevet inplamenteret, og så efter. 

For hvad jeg kan se så er koden det samme visuelt, og men forskellen er at koden nu er mere overskuelig, da der ikke skal skrives generalle funktioner for hver objekt, men kan skrives i en overklasse.
