### ISSUE TITLE
Patikel system

### ISSUE THREAD

**Issue by marc6030** [Wistoft2410/Digital-design---Spilprojekt#27]
# Task: Patikel system
### Forventet tid: 120 minutter
Lav et partikel system. af cirkler som, sprøjter partikler. som i kapitel 4 i nature of code. Som kan bruges til springvand og blod måske. og lava/magma

**Comment by Axedyson** [comment]
**Test af Task: Patikel system**
Det ser ud som at partikel systemet for vandet og fra vulkanen virker. Der er ikke fundet nogen bugs omkring de to dele af programmet. Det giver også god mening da partikel systemet er en del af baggrunden og bagrund har ikke nogen effekt på selve spil mekanikken
