### ISSUE TITLE
Point lyd

### ISSUE THREAD

**Issue by marc6030** [Wistoft2410/Digital-design---Spilprojekt#33]
# Point lyd
### Forventet tid: 60 minutter
Afspilning af ding lyd når man får point.

**Comment by SimonAxelsen** [comment]
**Test af lyd**
Test af lyd, når spillern kollidere med æggne. 
For at teste dette har jeg først hentet et ekstern libery, fra processings libery feature, og sat lyd på min pc. 
Det jeg gjorde var bare at spille spillet, og prøve at ramme æggene, når jeg så ramte nogle, blev der afspillet en "Ding" lyd, som indikere at jeg har fået et point. 

Hitboxen for hvornår man rammer et æg lavet som en ellipse, for både spillern og æggene, så nogle gange for man også et point når æggne rammer halen på spillern.
