### ISSUE TITLE
Game Menu

### ISSUE THREAD

**Issue by marc6030** [Wistoft2410/Digital-design---Spilprojekt#43]
# Collision with meteor
### Forventet tid: 60 minutter
Man skal kunne starte spillet fra en menu

**Comment by Axedyson** [comment]
**Test af menuen**
Når man starter spillet popper der en menu frem. Denne menu indeholder en `start` knap og en `exit game` knap. Begge knapper virker. Dog tager det lidt tid for `exit knap` at virke, men det har nok noget at gøre med at processing er langsom.
