### ISSUE TITLE
Liv til spilleren

### ISSUE THREAD

**Issue by SimonAxelsen** [Wistoft2410/Digital-design---Spilprojekt#5]
# Task: Liv til spilleren
### Forventet tid: 20 minutter
Spilleren skal have 5 liv. Når spilleren rammer en metaor mens spilleren er rød så mister spilleren en af sine liv.
Når spilleren har mistet alle sine 5 liv så har spilleren tabt spillet og spilleren vil blive præsenteret med følgende titel:
"GAME OVER" 
"Current highscore: \<brugerens highscore\>"

Følgende titel skal også præsenteres: "Press enter to play again"

Man skal altså have evnen til at trykke "enter" og spille et nyt spil!

**Comment by Axedyson** [comment]
Der er blevet lavet en afvigelse fra denne task:
Spilleren har lige nu kun 3 liv da det ser bedre ud på skærmen. Hvis spilleren havde 5 liv tror jeg det vil fylde for meget. Men det kan godt være at vi i fremtiden øger spillerens liv!

Når spilleren rammer en meteor så mister spilleren **et** liv.

Lige nu bliver der ikke præsenteret nogle titler efter man har tabt, bortset fra titlen i spil menuen når man starter spillet.

Man kan altså også starte om igen efter man har tabt.

**Comment by SimonAxelsen** [comment]
**Test af liv**
Det som skal testes er at spillern mister liv af at blive ramt. Når man har mistet alle liv skal spillern kunne starte igen og man skal kunne se highscore.
Man mister liv af at blive ramt, det eneste som kunne forbedres i nuværende tilstand er at der kommer en lyd effect når man bliver ramt. 
Når jeg dør helt (mister 3 liv) så kommer start menuen op igen, så jeg kan spille om igen så mange gange jeg vil, som det skal.
I forhold til highscore, så lige nu kan man kun se ens egen score som highscore, og den genstartes hver gang man starter et nyt spil. _I anden iteration er der lavet en issue til det._
