### ISSUE TITLE
Grøn og rød farve på timern

### ISSUE THREAD

**Issue by SimonAxelsen** [Wistoft2410/Digital-design---Spilprojekt#6]
# Grøn og rød farve på timern
### Forventet tid: 20 minutter
Timern skal kunne skifte farve mellem grøn og rød.
Vi arbejder med 10 sekunders intervaller (10 sekunder er 100% af den tid vi arbejder med).
Man er grøn i 9 sekunder (90%), og rød i et sekund (10%) til at starte med.
Efter et tids interval øger vi tiden man er rød med et sekund og reducerer tiden man er grøn med et sekund.

**Comment by Axedyson** [comment]
En ny person skal **assignes** til denne issue, da den skal testes af en ny person!

**Comment by SimonAxelsen** [comment]
**Test af farver på timern**
Timern skal have en grøn farve for 10 sekunder, og i de 10 sekunder, så skal der kun komme dejlige æg ned fra himlen, som giver points. Når timern efter 10 sekunder så bliver rød, skal der komme metatorer ned, som spillern skal undvige, ellers mister han liv.

Timern viser den røde og grønne farve godt, og de er en god kontrask til hinanden. 

I iteration 2, skal vi gøre sådan at timern bliver skiftevis mere og mere rød og mindre og mindre grøn. 

I interation 3, kan vi også lave en gul farve, hvor der både er æg og meteorer

**Comment by Axedyson** [comment]
**Test nr. 2 af farver på timern**
Det ser ud til at det stadig virker. Der er dog lavet en afvigelse fra denne task, da hvergang man modtager 10 point så bliver sværhedsgraden højere/svære på den måde at tidsmængden bliver øget med 1 sekund i den røde del, og den formindskes med 1 sekund i den grønne del!
