### ISSUE TITLE
Generate Meteorer 

### ISSUE THREAD

**Issue by SimonAxelsen** [Wistoft2410/Digital-design---Spilprojekt#7]
# Task: Meteor fra himlen
### Forventet tid: 20 minutter

Der skal "spawnes" Meteor fra himlen, som skal kunne kolliderer med dinosaurussen som spilleren styrer. Når meteor rammer spilleren skal meteor bare "despawne"!

**Comment by Axedyson** [comment]
Det er lavet nu meteorerne "despawner" når de rammer spilleren!

**Comment by SimonAxelsen** [comment]
**Test af meteor**
Meteorerne skal kun spawne når timern er rød, og så skal man undvige dem, ellers mister man liv. Funktionen med at de kun spawner i det røde interval virker, og når jeg bliver ramt af dem, kan jeg også se at et liv forsvinder.
Når jeg rammer meteoren forsvinder den også meget hurtigt efter,  istedet for at forsvinde ned i jorden. 

Meteorerne kommer også i et reglmæssigt, fint niveau, så det ikek er for let at undvige, men stadigvæk en udfordring
