### ISSUE TITLE
Dinosaur movements

### ISSUE THREAD

**Issue by SimonAxelsen** [Wistoft2410/Digital-design---Spilprojekt#9]
# Task: Dinosaur movements
### Opdateret forventet tid:  30 minutter

Dinosaurussen som styres af spilleren laves. Denne dinosaurussen skal kunne bevæge sig ved brug af tre knapper:
Pil op, pil til venstre og pil til højre knappen.
Disse knapper skal skal kunne flytte den til højre og til venstre samt få den til at "hoppe" op i luften.

**Comment by SimonAxelsen** [comment]
**Test af movement på dino**
Testen af bevægelse af bolden, som senere bliver til en dinosurus er lavet på den måde at jeg har pull koden ned og prøvet den. Den måde som jeg har prøvet movement på er ved først at prøve hver funktion individuelt, som alle virker fint nok for sig selv. Hoppe funktionen er dog lidt usansynlig, på hvor højt man hopper. 

Når jeg prøver flere funktioner på samme tid kan der godt opstå fejl, ved at efter et hop, kan bolden godt komme til at gå den forkerte vej for et stykke tid. En anden bug som jeg støtte ind i, var at nolge gange sad bolden fast i en hoppe bevægelse, selvom jeg holdte venstre/højre knap inde.

Jeg kan dermed konkludere at movement umelbart virker fint, men der kan godt opstå bugs, og bugs opstå mere hvis jeg opsøger dem.

**Comment by Axedyson** [comment]
Ok jeg skal nok løse den på et tidspunkt!!

**Comment by SimonAxelsen** [comment]
**Ny test af dino movement**
Der er lavet en commit til movement, som har fixet den måde som bolden hopper på, så når den rammer jorden, så bliver tyndekraften til 0, så bolden ikke hele tiden skal genplaceres på jorden. Dette gør at når man hopper, så sker der ikke nogle fejl, og alle hoppene er samme højde.

I forhold til at bevæge sig højre og venstre, så er der samme bugs.

**Comment by SimonAxelsen** [comment]
**Test efter fix**
Det som stadigvæk ikke virkede sidste test var at der ikke kunne trykke på to krapper på samme tid, så man kunne ikke hoppe og gå til siden på samme tid, og det var svært at skifte retning. 
De problemer er nu fixet.
